filter:
    excluded_paths: [tests/*, bin/*, assets/*, languages/* ]
    dependency_paths:
        - wordpress/
tools:
    external_code_coverage: false
    php_code_coverage: true
checks:
    php:
        code_rating: true
build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            tests:
                override:
                    - php-scrutinizer-run
